import { DefenseSystem, DefenseSystemInfo } from '@/types';

export const DEFENSE_SYSTEMS: Record<DefenseSystem, DefenseSystemInfo> = {
  [DefenseSystem.ANGIOGENESIS]: {
    id: 'angiogenesis',
    name: DefenseSystem.ANGIOGENESIS,
    displayName: 'Angiogenesis',
    icon: '🩸',
    description: 'Blood vessel formation and healthy circulation. Supports starving harmful cells while feeding healthy ones.',
    keyFoods: [
      'Tomatoes',
      'Soy',
      'Red Wine',
      'Dark Chocolate',
      'Berries',
      'Apples',
      'Olive Oil',
      'Green Tea',
    ],
    nutrients: [
      'Lycopene',
      'Resveratrol',
      'Genistein',
      'Ellagic Acid',
      'EGCG',
    ],
    color: 'angiogenesis',
    bgColor: 'bg-angiogenesis-light',
    borderColor: 'border-angiogenesis',
    textColor: 'text-angiogenesis-dark',
  },
  [DefenseSystem.REGENERATION]: {
    id: 'regeneration',
    name: DefenseSystem.REGENERATION,
    displayName: 'Regeneration',
    icon: '🔄',
    description: 'Tissue and organ regeneration through stem cell activation. Helps your body heal and rebuild itself.',
    keyFoods: [
      'Wild Salmon',
      'Mangoes',
      'Black Tea',
      'Coffee',
      'Walnuts',
      'Dark Chocolate',
      'Beer',
      'Omega-3 Rich Foods',
    ],
    nutrients: [
      'Omega-3 Fatty Acids',
      'Vitamin D',
      'Polyphenols',
      'Curcumin',
      'Resveratrol',
    ],
    color: 'regeneration',
    bgColor: 'bg-regeneration-light',
    borderColor: 'border-regeneration',
    textColor: 'text-regeneration-dark',
  },
  [DefenseSystem.MICROBIOME]: {
    id: 'microbiome',
    name: DefenseSystem.MICROBIOME,
    displayName: 'Microbiome',
    icon: '🦠',
    description: 'Gut bacteria health and digestive wellness. Supports beneficial bacteria that protect your health.',
    keyFoods: [
      'Kimchi',
      'Greek Yogurt',
      'Sauerkraut',
      'Tempeh',
      'Kombucha',
      'Kefir',
      'Miso',
      'Sourdough Bread',
    ],
    nutrients: [
      'Probiotics',
      'Prebiotics (Fiber)',
      'Polyphenols',
      'Omega-3s',
      'Vitamins',
    ],
    color: 'microbiome',
    bgColor: 'bg-microbiome-light',
    borderColor: 'border-microbiome',
    textColor: 'text-microbiome-dark',
  },
  [DefenseSystem.DNA_PROTECTION]: {
    id: 'dna-protection',
    name: DefenseSystem.DNA_PROTECTION,
    displayName: 'DNA Protection',
    icon: '🧬',
    description: 'Repairing DNA damage and slowing aging. Protects genetic material from harmful mutations.',
    keyFoods: [
      'Broccoli',
      'Kale',
      'Cauliflower',
      'Green Tea',
      'Turmeric',
      'Brussels Sprouts',
      'Carrots',
      'Berries',
    ],
    nutrients: [
      'Sulforaphane',
      'EGCG',
      'Curcumin',
      'Anthocyanins',
      'Beta-Carotene',
    ],
    color: 'dna',
    bgColor: 'bg-dna-light',
    borderColor: 'border-dna',
    textColor: 'text-dna-dark',
  },
  [DefenseSystem.IMMUNITY]: {
    id: 'immunity',
    name: DefenseSystem.IMMUNITY,
    displayName: 'Immunity',
    icon: '🛡️',
    description: 'Fighting infection and cancer. Strengthens immune response against harmful invaders.',
    keyFoods: [
      'Shiitake Mushrooms',
      'Garlic',
      'Onions',
      'Ginger',
      'Citrus Fruits',
      'Blueberries',
      'Pomegranate',
      'Broccoli',
    ],
    nutrients: [
      'Beta-Glucans',
      'Allicin',
      'Vitamin C',
      'Zinc',
      'Selenium',
    ],
    color: 'immunity',
    bgColor: 'bg-immunity-light',
    borderColor: 'border-immunity',
    textColor: 'text-immunity-dark',
  },
};

export const DEFENSE_SYSTEM_ARRAY = Object.values(DEFENSE_SYSTEMS);

export const getDefenseSystemInfo = (system: DefenseSystem): DefenseSystemInfo => {
  return DEFENSE_SYSTEMS[system];
};